In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/honda_car_selling.csv')

In [3]:
df

,Year,kms Driven,Fuel Type,Suspension,Price,Car Model
0,2019,19006 kms,Petrol,Automatic,9.29 Lakh,Honda City V CVT
1,2021,11936 kms,Petrol,Automatic,13.95 Lakh,Honda City ZX CVT
2,2018,29635 kms,Petrol,Automatic,9.95 Lakh,Honda City i-VTEC CVT ZX
3,2020,16163 kms,Petrol,Automatic,13.26 Lakh,Honda City ZX CVT
4,2015,105114 kms,Petrol,Manual,5.68 Lakh,Honda City i VTEC V
...,...,...,...,...,...,...
994,2007,90000 kms,Petrol,Manual,1.22 Lakh,Honda Civic 1.8 V MT
995,2016,31500 kms,Petrol,Manual,4.25 Lakh,Honda Amaze S i-VTEC
996,2017,39735 kms,Petrol,Manual,5.10 Lakh,Honda Amaze S Petrol
997,2017,36000 kms,Petrol,Manual,6.10 Lakh,Honda City i VTEC S
998,2015,35341 kms,Diesel,Manual,3 Lakh,Honda Amaze S i-Dtech

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        999 non-null    int64
 1   kms Driven  999 non-null    object
 2   Fuel Type   999 non-null    object
 3   Suspension  999 non-null    object
 4   Price       999 non-null    object
 5   Car Model   999 non-null    object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

In [11]:
for col in ['Price', 'kms Driven']:
    df[col] = df[col].str.replace(',', '').str.strip()  # remove commas and extra spaces

    if col == 'Price':
        df[col] = df[col].str.replace('Lakh', '', regex=False).astype(float) * 100000
    elif col == 'kms Driven':
        df[col] = df[col].str.replace('kms', '', regex=False).astype(int)

In [12]:
df

,Year,kms Driven,Fuel Type,Suspension,Price,Car Model
0,2019,19006,Petrol,Automatic,929000.0,Honda City V CVT
1,2021,11936,Petrol,Automatic,1395000.0,Honda City ZX CVT
2,2018,29635,Petrol,Automatic,995000.0,Honda City i-VTEC CVT ZX
3,2020,16163,Petrol,Automatic,1326000.0,Honda City ZX CVT
4,2015,105114,Petrol,Manual,568000.0,Honda City i VTEC V
...,...,...,...,...,...,...
994,2007,90000,Petrol,Manual,122000.0,Honda Civic 1.8 V MT
995,2016,31500,Petrol,Manual,425000.0,Honda Amaze S i-VTEC
996,2017,39735,Petrol,Manual,510000.0,Honda Amaze S Petrol
997,2017,36000,Petrol,Manual,610000.0,Honda City i VTEC S
998,2015,35341,Diesel,Manual,300000.0,Honda Amaze S i-Dtech

In [13]:
from sklearn.preprocessing import LabelEncoder


# Initialize LabelEncoder
le = LabelEncoder()

# Columns to encode
cols_to_encode = ['Fuel Type', 'Suspension', 'Car Model']

# Encode each column using a for loop
for col in cols_to_encode:
    df[col] = le.fit_transform(df[col])

In [14]:
df

     Year  kms Driven  Fuel Type  Suspension      Price  Car Model
0    2019       19006          2           0   929000.0        101
1    2021       11936          2           0  1395000.0        107
2    2018       29635          2           0   995000.0        131
3    2020       16163          2           0  1326000.0        107
4    2015      105114          2           1   568000.0        123
..    ...         ...        ...         ...        ...        ...
994  2007       90000          2           1   122000.0        143
995  2016       31500          2           1   425000.0         30
996  2017       39735          2           1   510000.0         25
997  2017       36000          2           1   610000.0        121
998  2015       35341          1           1   300000.0         29

[999 rows x 6 columns]

In [15]:
df.isnull().sum()

Year          0
kms Driven    0
Fuel Type     0
Suspension    0
Price         0
Car Model     0
dtype: int64

In [16]:
df[df.duplicated()]

     Year  kms Driven  Fuel Type  Suspension         Price  Car Model
223  2018       43326          2           1  4.850000e+05          9
515  2017       51000          2           0  8.990000e+05        131
735  2021       38352          2           1  7.850000e+05         47
739  2020       60714          2           1  6.900000e+05         25
786  2012       48000          2           1  2.750000e+05         64
962  2008       80000          2           1  2.000000e+05        143
980  2016       28000          2           1  4.700000e+05         62
981  2017       30000          2           1  4.500000e+05         30
982  2008       80000          2           1  2.000000e+05        143
983  2016       35000          1           1  6.200000e+05        158
984  2008      110000          2           1  1.250000e+05        143
985  2015       37326          2           1  5.000000e+05        150
986  2018       60000          1           1  9.000000e+05        126
987  2007      110000          2           1  4.500000e+05         80
988  2016       50000          2           0  7.800000e+05        119
989  2006      110000          2           1  1.800000e+05         97
990  2017       16665          2           0  1.150000e+06        130
991  2013      110000          1           1  3.350000e+05         11
992  2019       47297          2           0  1.500000e+06        147
993  2006      186719          2           1  9.000000e+09         97
994  2007       90000          2           1  1.220000e+05        143
995  2016       31500          2           1  4.250000e+05         30
996  2017       39735          2           1  5.100000e+05         25
997  2017       36000          2           1  6.100000e+05        121
998  2015       35341          1           1  3.000000e+05         29

In [17]:
df = df.drop_duplicates()

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 974 entries, 0 to 979
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        974 non-null    int64
 1   kms Driven  974 non-null    int64
 2   Fuel Type   974 non-null    int64
 3   Suspension  974 non-null    int64
 4   Price       974 non-null    float64
 5   Car Model   974 non-null    int64
dtypes: float64(1), int64(5)
memory usage: 53.3 KB

In [19]:
from scipy import stats

# Make a copy of the DataFrame
df_stat = df.copy()

In [21]:
qa_results = []

# 1. T-test: Automatic vs Manual car prices
auto_prices = df_stat[df_stat['Suspension'] == 0]['Price']
manual_prices = df_stat[df_stat['Suspension'] == 1]['Price']
t_stat, p_val = stats.ttest_ind(auto_prices, manual_prices, equal_var=False)
qa_results.append(("Automatic vs Manual car prices", p_val))
print("T-test results:")
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_val}")

T-test results:
T-statistic: -2.382662296997079
P-value: 0.01743480719829331

In [25]:
# Assuming Petrol = 2 and Diesel = 0 from earlier encoding
petrol_kms = df_stat[df_stat['Fuel Type'] == 2]['kms Driven']
diesel_kms = df_stat[df_stat['Fuel Type'] == 0]['kms Driven']

# T-test
t_stat, p_val = stats.ttest_ind(petrol_kms, diesel_kms, equal_var=False, nan_policy='omit')

# Append result
qa_results.append(("Petrol vs Diesel kilometers driven", p_val))
print("\nT-test results:")
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_val}")

# 2. T-test: Petrol vs Diesel kms driven

T-test results:
T-statistic: nan
P-value: nan

In [26]:
# 3. Chi-Square: Fuel Type vs Suspension
contingency1 = pd.crosstab(df_stat['Fuel Type'], df_stat['Suspension'])
chi2, p_val, _, _ = stats.chi2_contingency(contingency1)
qa_results.append(("Fuel Type vs Suspension", p_val))
print("\nChi-Square results:")
print(f"Chi-Square statistic: {chi2}")
print(f"P-value: {p_val}")

Chi-Square results:
Chi-Square statistic: 56.808071624498034
P-value: 4.616193264276976e-13

In [27]:
# 4. ANOVA: Price across fuel types
groups = [df_stat[df_stat['Fuel Type'] == i]['Price'] for i in df_stat['Fuel Type'].unique()]
f_stat, p_val = stats.f_oneway(*groups)
qa_results.append(("Price across Fuel Types (ANOVA)", p_val))
print("\nANOVA results:")
print(f"F-statistic: {f_stat}")
print(f"P-value: {p_val}")

ANOVA results:
F-statistic: 0.7298912901166758
P-value: 0.482225618065826

In [28]:
# 5. Chi-Square: Car Model vs Suspension
contingency2 = pd.crosstab(df_stat['Car Model'], df_stat['Suspension'])
chi2, p_val, _, _ = stats.chi2_contingency(contingency2)
qa_results.append(("Car Model vs Suspension", p_val))
print("\nChi-Square results:")
print(f"Chi-Square statistic: {chi2}")
print(f"P-value: {p_val}")

Chi-Square results:
Chi-Square statistic: 974.0000000000001
P-value: 1.9622307489494833e-108

In [29]:
# 6. T-test: Older (<2015) vs Newer (>=2015) car prices
old_cars = df_stat[df_stat['Year'] < 2015]['Price']
new_cars = df_stat[df_stat['Year'] >= 2015]['Price']
t_stat, p_val = stats.ttest_ind(old_cars, new_cars, equal_var=False)
qa_results.append(("Old vs New car prices", p_val))
print("\nT-test results:")
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_val}")

T-test results:
T-statistic: 2.3906759894187144
P-value: 0.01725698841769221

In [30]:
# 7. ANOVA: Kilometers driven across car years
year_groups = [df_stat[df_stat['Year'] == y]['kms Driven'] for y in df_stat['Year'].unique() if len(df_stat[df_stat['Year'] == y]) > 5]
f_stat, p_val = stats.f_oneway(*year_groups)
qa_results.append(("KMs Driven across Years (ANOVA)", p_val))
print("\nANOVA results:")
print(f"F-statistic: {f_stat}")
print(f"P-value: {p_val}")

ANOVA results:
F-statistic: 11.973155957531203
P-value: 1.9414977450000263e-27

In [31]:
# 8. Chi-Square: Car Model vs Fuel Type
contingency3 = pd.crosstab(df_stat['Car Model'], df_stat['Fuel Type'])
chi2, p_val, _, _ = stats.chi2_contingency(contingency3)
qa_results.append(("Car Model vs Fuel Type", p_val))
print("\nChi-Square results:")
print(f"Chi-Square statistic: {chi2}")
print(f"P-value: {p_val}")

Chi-Square results:
Chi-Square statistic: 1944.9003414621384
P-value: 1.0067397569835941e-213

In [32]:
# 9. ANOVA: Price across top 3 car models
top3_models = df_stat['Car Model'].value_counts().nlargest(3).index
model_groups = [df_stat[df_stat['Car Model'] == m]['Price'] for m in top3_models]
f_stat, p_val = stats.f_oneway(*model_groups)
qa_results.append(("Price across Top 3 Car Models (ANOVA)", p_val))
print("\nANOVA results:")
print(f"F-statistic: {f_stat}")
print(f"P-value: {p_val}")

ANOVA results:
F-statistic: 229.14668456973092
P-value: 5.114496259604695e-41

In [33]:
# 10. T-test: Price for cars above vs below 50,000 kms
above_50k = df_stat[df_stat['kms Driven'] > 50000]['Price']
below_50k = df_stat[df_stat['kms Driven'] <= 50000]['Price']
t_stat, p_val = stats.ttest_ind(above_50k, below_50k, equal_var=False)
qa_results.append(("Price for >50K vs <=50K km", p_val))
print("\nT-test results:")
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_val}")

T-test results:
T-statistic: 1.203464069992452
P-value: 0.22909616698144009

In [34]:
# Print results
for i, (question, p_val) in enumerate(qa_results, 1):
    result = "Yes" if p_val < 0.05 else "No"
    print(f"{i}. {question}")
    print(f"   p-value: {p_val:.4f} âž¤ Significant? {result}\n")

1. Automatic vs Manual car prices
   p-value: 0.0174 âž¤ Significant? Yes

2. Petrol vs Diesel kilometers driven
   p-value: nan âž¤ Significant? No

3. Fuel Type vs Suspension
   p-value: 0.0000 âž¤ Significant? Yes

4. Price across Fuel Types (ANOVA)
   p-value: 0.4822 âž¤ Significant? No

5. Car Model vs Suspension
   p-value: 0.0000 âž¤ Significant? Yes

6. Old vs New car prices
   p-value: 0.0173 âž¤ Significant? Yes

7. KMs Driven across Years (ANOVA)
   p-value: 0.0000 âž¤ Significant? Yes

8. Car Model vs Fuel Type
   p-value: 0.0000 âž¤ Significant? Yes

9. Price across Top 3 Car Models (ANOVA)
   p-value: 0.0000 âž¤ Significant? Yes

10. Price for >50K vs <=50K km
   p-value: 0.2291 âž¤ Significant? No